resources:
  - name: gitrepo_res
    type: gitRepo
    repoPath: deepikasl/vt1
    configuration:
      integrationName: github-subint
      branches:
        except: random
    initialVersion:
      sha: master
 
  - name: image_res
    type: image
    imageName: "library/nginx"
    configuration:
      integrationName: docker-int
    initialVersion:
      imageTag: latest

pipelines:
  - name: pipe_1
    setup:
      runtime: onHost
    steps:
      - name: step1_A
        type: bash
        configuration:
          affinityGroup: test_group 
        setup:
          environmentVariables:
            normal:
              - ENV1: value1
              - ENV2: value2
              - ENV3: value3
              - ENV4: value4
              - ENV5: value5
            encrypted:
              - SECURE_ENV1: test_value
              - SECURE_ENV2: test_value
          runtime:            
            type: image
            image:
              auto: true
              language: java
              versions: v1.1
            custom: 
              name: test
              tag:  test
              options: test
        requires:
          integrations:
            - docker-int
          resources:
            - image_res
        triggeredBy:
          resources:
            - gitrepo_res 
        execution:
          onExecute:
            - echo "executing..."

      - name: step1_B
        type: bash
        configuration:
          affinityGroup: test_group      
        setup:
          runtime: onHost
        triggeredBy:
          steps:
            - step1_A 
        execution:
          onExecute:
            - echo "executing..."

      - name: step1_C
        type: bash
        configuration:
          affinityGroup: test_group      
        setup:
          runtime: onHost
        triggeredBy:
          steps:
            - step1_A 
        execution:
          onExecute:
            - echo "executing..."
